"""Measure the detour factor used to time routes that scenarios add.

An added route is timed from straight-line distances between its stops, so the factor that turns
those into road distances should come from the city, not from a textbook. Consecutive stops of
real bus patterns are a direct sample: the walk-network distance between them (OSM streets)
divided by the straight line. Walking distance ignores one-way streets and turn restrictions, so
it slightly understates the bus's road distance; the mean is reported as the suggested factor
rather than the median for that reason.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import numpy.typing as npt
import polars as pl

from glacies.routing.network import load_walk_graph
from glacies.validate.gtfs.common import haversine_m


@dataclass(frozen=True)
class DetourSample:
    hops: int  # distinct consecutive-stop pairs in the length range
    sampled: int
    ratios: npt.NDArray[np.float64]  # walk distance / straight line, for hops with a walk path
    min_m: float
    max_m: float
    seed: int
    modes: tuple[str, ...]

    def percentile(self, q: float) -> float:
        return float(np.percentile(self.ratios, q))

    @property
    def mean(self) -> float:
        return float(self.ratios.mean())


def detour_ratios(
    city_dir: Path,
    *,
    samples: int,
    seed: int,
    modes: tuple[str, ...] = ("bus",),
    min_m: float = 200.0,
    max_m: float = 2000.0,
) -> DetourSample:
    transit = city_dir / "transit"
    routes = pl.read_parquet(transit / "routes.parquet", columns=["route_idx", "mode"])
    stops = pl.read_parquet(transit / "stops.parquet", columns=["stop_idx", "lat", "lon"])
    hops = (
        pl.read_parquet(transit / "pattern_stops.parquet")
        .join(pl.read_parquet(transit / "patterns.parquet"), on="pattern_idx")
        .join(routes.filter(pl.col("mode").is_in(list(modes))), on="route_idx", how="semi")
        .sort("pattern_idx", "position")
        .with_columns(pl.col("stop_idx").shift(-1).over("pattern_idx").alias("to_stop"))
        .drop_nulls("to_stop")
        .select("stop_idx", "to_stop")
        .unique()
        .sort("stop_idx", "to_stop")
        .join(stops, on="stop_idx")
        .join(stops, left_on="to_stop", right_on="stop_idx", suffix="_to")
        .with_columns(
            haversine_m(pl.col("lat"), pl.col("lon"), pl.col("lat_to"), pl.col("lon_to")).alias(
                "straight_m"
            )
        )
        .filter(pl.col("straight_m").is_between(min_m, max_m))
        .sort("stop_idx", "to_stop")
    )
    sample = hops.sample(n=min(samples, hops.height), seed=seed)

    walk = load_walk_graph(city_dir / "walk")
    links = pl.read_parquet(city_dir / "walk" / "stop_links.parquet")
    link = {r["stop_idx"]: r for r in links.iter_rows(named=True)}
    ratios: list[float] = []
    for a, b, straight in sample.select("stop_idx", "to_stop", "straight_m").iter_rows():
        if a not in link or b not in link:
            continue
        start = link[a]
        found, metres = walk.stops_within(
            start["edge_idx"], start["fraction"], start["distance_m"], 3 * straight + 500
        )
        hit = metres[found == b]
        if hit.size:
            ratios.append(float(hit[0]) / straight)
    return DetourSample(
        hops=hops.height,
        sampled=sample.height,
        ratios=np.array(ratios, dtype=np.float64),
        min_m=min_m,
        max_m=max_m,
        seed=seed,
        modes=modes,
    )


def markdown(result: DetourSample, header: str) -> str:
    r = result
    lines = [
        "# Detour factor for routes added by scenarios",
        "",
        header,
        "",
        "Generated by `glacies scenario calibrate`. Consecutive stops of "
        f"{'/'.join(r.modes)} patterns, {r.min_m:.0f}-{r.max_m:.0f} m apart in a straight line: "
        f"{r.hops:,} distinct pairs, {r.sampled:,} sampled (seed {r.seed}), "
        f"{r.ratios.size:,} with a walk path between them.",
        "",
        "| Statistic | Walk distance / straight line |",
        "|---|---|",
        *(f"| p{q} | {r.percentile(q):.2f} |" for q in (10, 25, 50, 75, 90)),
        f"| mean | {r.mean:.2f} |",
        "",
        "Walking distance ignores one-way streets and turn restrictions, so it understates a bus's "
        "road distance. The suggested `[scenario] detour_factor` is therefore the mean "
        f"(**{r.mean:.2f}**), not the median. The value in city.toml is still **Assumed**: it "
        "is a measured property of existing stop spacing, applied to routes that do not exist.",
        "",
    ]
    return "\n".join(lines)
